Add 'Spotify for Creators' impressions support
openpodcast/pipelines pull request #90
Opened 2024-12-24 00:14 UTC by mre

2025-02-05 10:46 UTC, woolfg requested changes
great. we just have to make sure to set the right date range for the api

2025-02-05 10:46 UTC, woolfg commented on anchor/job/__main__.py
> +        start_date=date_range.start,
it is always last 30 days. so we have to send the correct date range to the api as the values are stored with this date range in the DB

2025-03-03 09:42 UTC, mre commented on anchor/job/__main__.py
> +        start_date=date_range.start,
fixed

2025-03-03 09:46 UTC, mre commented
> great. we just have to make sure to set the right date range for the api

done (as discussed during pair-programming)

2025-03-03 09:47 UTC, mre commented
⚠️ Before merging, we need to add an impressions API endpoint. See https://github.com/openpodcast/api/issues/147

2025-08-19 21:16 UTC, woolfg approved these changes
lgtm

2025-08-29 18:20 UTC, mre commented
This is outdated.

2025-08-29 18:20 UTC, closed without merging

2025-08-30 11:15 UTC, woolfg commented
see https://github.com/openpodcast/anchor-connector/pull/5#issuecomment-3239196595

as it is the same format a spotify we could use the same table as spotify and just adapt the API or even split the payload and send it to the spotify api? we hast have to think how to handle the different ids ... but I have seen that even the spotify ids are used sometimes in anchor, so i guess they move towards the spotify echosystem anyways. we could rely on the spotify ids for this part already. we just need a mapping table (if not already present).